API departures, connector RENNES
hove-io/forseti pull request #96
Opened 2022-07-01 07:03 UTC by julienbt

Add a new connector for the API `departures`

2022-07-04 14:54 UTC, kadhikari requested changes

2022-07-04 14:54 UTC, kadhikari commented on internal/departures/rennes/buslines/buslines.go
> +package buslines
Here we may have Lines of different modes like bus, metro, train. Better rename `buslines.go` to `lines.go`.
Delete preceding work Bus or bus everywhere.

2022-07-04 14:54 UTC, kadhikari commented on internal/departures/rennes/scheduledtimes/scheduledtimes.go
> +package scheduledtimes
Rename as stoptimes.go and renames all concerned variables

2022-07-04 14:54 UTC, kadhikari commented on internal/departures/rennes/scheduledtimes/scheduledtimes_test.go
> +package scheduledtimes
Same as above

2022-07-04 14:54 UTC, kadhikari commented on internal/departures/rennes/routes/routes.go
> +	BusLineInternalId string
```suggestion
	LineInternalId string
```

2022-07-04 14:54 UTC, kadhikari commented on internal/departures/rennes/dbinternallinks/dbinternallinks_test.go
> +package dbinternallinks
Same as above

2022-07-05 08:04 UTC, julienbt commented on internal/departures/rennes/buslines/buslines_test.go
> +package buslines
Done

2022-07-05 08:04 UTC, julienbt commented on internal/departures/rennes/buslines/buslines.go
> +package buslines
Done

2022-07-05 08:07 UTC, julienbt commented on internal/departures/rennes/routes/routes.go
> +	BusLineInternalId string
Done

2022-07-05 08:08 UTC, julienbt commented on internal/departures/rennes/rennes.go
> +	BusLineId        string
Done

2022-07-05 08:44 UTC, julienbt commented on internal/departures/rennes/scheduledtimes/scheduledtimes.go
> +package scheduledtimes
Done

2022-07-05 08:44 UTC, julienbt commented on internal/departures/rennes/dbinternallinks/dbinternallinks.go
> +package dbinternallinks
Done

2022-07-05 08:44 UTC, julienbt commented on internal/departures/rennes/scheduledtimes/scheduledtimes_test.go
> +package scheduledtimes
Done

2022-07-05 08:52 UTC, julienbt commented on internal/departures/rennes/dbinternallinks/dbinternallinks.go
> +package dbinternallinks
@kadhikari
`routestoppoint.go` or `routestoppoints.go`?

2022-07-05 09:42 UTC, julienbt commented on internal/departures/rennes/dbinternallinks/dbinternallinks.go
> +package dbinternallinks
I have chosen `routestoppoints.go`

2022-07-05 09:42 UTC, julienbt commented on internal/departures/rennes/dbinternallinks/dbinternallinks.go
> +package dbinternallinks
Done

2022-07-05 09:42 UTC, julienbt commented on internal/departures/rennes/dbinternallinks/dbinternallinks_test.go
> +package dbinternallinks
Done

2022-07-06 09:34 UTC, kadhikari approved these changes

2022-07-06 09:35 UTC, merged